const twoSum = require('./questions/question1')
const addTwoNumbers = require('./questions/question2')
const lengthOfLongestSubstring = require('./questions/question3')
const findMedianSortedArrays = require('./questions/question4')
const longestPalindrome = require('./questions/question5')
const convert = require('./questions/question6')
const reverse = require('./questions/question7')
const myAtoi = require('./questions/question8')
const isPalindrome = require('./questions/question9')
const isMatch = require('./questions/question10')

console.log(isMatch("aa", "a"))
console.log(isMatch("aa", "a*"))
console.log(isMatch("ab", ".*"))